# In order to install old Rubies, we need to use old Ubuntu distibution.
dist: trusty
language: ruby
script: "script/test_all"
email: false
before_install:
  - script/update_rubygems_and_install_bundler
bundler_args: "--standalone --binstubs --without documentation"
rvm:
  - 1.8.7
  - 1.9.2
  - ree
env:
  - JRUBY_OPTS='--dev'
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
